
// //! Autogenerated weights for `pallet_etf`
// //!
// //! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
// //! DATE: 2023-07-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
// //! WORST CASE MAP SIZE: `1000000`
// //! HOSTNAME: `DESKTOP-RN9BJOQ`, CPU: `Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz`
// //! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// // Executed Command:
// // ./target/release/node-template
// // benchmark
// // pallet
// // --chain
// // dev
// // --wasm-execution=compiled
// // --pallet
// // pallet_etf
// // --extrinsic
// // *
// // --steps
// // 50
// // --repeat
// // 20
// // --output
// // bin/node-template/pallets/etf/src/weight.rs

// #![cfg_attr(rustfmt, rustfmt_skip)]
// #![allow(unused_parens)]
// #![allow(unused_imports)]
// #![allow(missing_docs)]

// use frame_support::{traits::Get, weights::Weight};
// use core::marker::PhantomData;
// use crate as pallet_etf;

// pub trait WeightInfo {
// 	fn update_ibe_params() -> Weight;
// }

// /// Weight functions for `pallet_etf`.
// pub struct SubstrateWeightInfo<T>(PhantomData<T>);
// impl<T: frame_system::Config> WeightInfo for SubstrateWeightInfo<T> {
// 	/// Storage: Etf IBEParams (r:0 w:1)
// 	/// Proof Skipped: Etf IBEParams (max_values: Some(1), max_size: None, mode: Measured)
// 	fn update_ibe_params() -> Weight {
// 		// Proof Size summary in bytes:
// 		//  Measured:  `0`
// 		//  Estimated: `0`
// 		// Minimum execution time: 80_700_000 picoseconds.
// 		Weight::from_parts(81_500_000, 0)
// 			.saturating_add(Weight::from_parts(0, 0))
// 			.saturating_add(T::DbWeight::get().writes(1))
// 	}
// }
